config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  root 'users#show'
  post '/signup', to: 'users#create'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  delete 'delete_closet', to: 'users#delete_closet'
  delete 'delete_outfits_history', to: 'users#delete_outfits_history'
  resources :users
  resources :sessions
  
  get '/inputs', to: 'inputs#index'
  get 'user_input_page/:id', to: 'inputs#index', as: 'user_input'
  post 'send_message', to: 'inputs#send_message'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/chat_message.rb
class ChatMessage < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  has_one_attached :outfits_history
  has_one_attached :closet

  validates :email, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def authorize
    redirect_to new_session_path unless current_user
    # unless User.find(session[:user_id]) if session[:user_id]
  end

  # Currently not being used – may be deleted
  def render_unprocessable_entity_response(exception)
    render json: { errors: exception.record.errors.full_messages }, status: :unprocessable_entity
  end

end

app/controllers/inputs_controller.rb
class InputsController < ApplicationController
  def index
    session[:user_id] = params[:id]
    @user = User.find(session[:user_id])
  end
  
  def send_message 
    user = User.find(session[:user_id])
    
    if params[:message].present?
      response = OpenaiService.new.handle_message(params[:message], process_xlsx(user.outfits_history), user.closet_embedding)
      render turbo_stream: turbo_stream.append("response_area", partial: "inputs/response", locals: { response: response })

    else
      render json: { error: 'No question provided' }, status: :unprocessable_entity
    end
  rescue ActiveRecord::RecordNotFound => e
    Rails.logger.error("User not found: #{e.message}")
    render json: { error: "User not found" }, status: :not_found
  end

  # def process_file
  #   uploaded_io = params[:user][:picture]
  #   File.open(Rails.root.join('public', 'uploads', uploaded_io.original_filename), 'w') do |file|
  #     file.write(uploaded_io.read)
  #   end
  # end

  def process_xlsx(file)
    # Temporarily download the xlsx file
    temp_file = Tempfile.new
    temp_file.binmode
    temp_file.write(file.download)
    temp_file.rewind
    
    xlsx = Roo::Spreadsheet.open(temp_file.path, extension: :xlsx)
    sheet = xlsx.sheet(0)
    data = sheet.each_row_streaming.map { |row| row.map(&:value) }.flatten.join(' ')

    data
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
  end

  def create
    session_params = params.permit(:email, :password)
    @user = User.find_by(email: session_params[:email])
    if @user && @user.authenticate(session_params[:password])
      session[:user_id] = @user.id
      redirect_to @user
    else
      render json: { errors: "Login invalid" }
      # flash[:notice] = "Login is invalid. Please log in again."
      redirect_to new_session_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You have successfully been logged out"
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authorize, except: [:new, :create]

  def index
    @users = User.all
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(session[:user_id])
    if @user.nil?
      redirect_to login_path
    end
  end

  def create
    @user = User.new(params.require(:user).permit(:name, :email, :password))
    if @user.save

      redirect_to root_path
    else
      render json: { error: @user.errors.full_messages }, status: :unprocessable_entity
    end
  end

  def delete_closet
    @user = User.find(session[:user_id])
    if @user.closet.attached?
      if @user.closet.purge.nil?
        Rails.logger.info("")
        redirect_to root_path
      end
    end
  end

  def delete_outfits_history
    @user = User.find(session[:user_id])
    if @user.outfits_history.attached?
      if @user.outfits_history.purge.nil?
        Rails.logger.info("")
        redirect_to root_path
      end
    end
  end

  def update
    @user = User.find(params[:id])

    if params[:user][:closet].present?
      if @user.update(closet: params[:user][:closet])
        Rails.logger.info("Closet uploaded successfully!")
      else
        Rails.logger.error(@user.errors.full_messages)
      end

    elsif params[:user][:outfits_history].present?
      if @user.update(outfits_history: params[:user][:outfits_history])
        Rails.logger.info("Outfits history uploaded successfully!") 
      else
        Rails.logger.error(@user.errors.full_messages)
      end

    else
      render json: { error: "No file provided" }, status: :bad_request
    end
  end


  private

  def user_params(attribute)
    params.require(:user).permit(attribute)
  end

  def process_xlsx(file)
    # Temporarily download the xlsx file
    temp_file = Tempfile.new
    temp_file.binmode
    temp_file.write(file.download)
    temp_file.rewind
    
    xlsx = Roo::Spreadsheet.open(temp_file.path, extension: :xlsx)
    sheet = xlsx.sheet(0)
    data = sheet.each_row_streaming.map { |row| row.map(&:value) }.flatten.join(' ')

    data
  end

  # Currently ONLY for an excel file
  # def process_and_embed(file)
  #   # Temporarily download the xlsx file
  #   temp_file = Tempfile.new
  #   temp_file.binmode
  #   temp_file.write(file.download)
  #   temp_file.rewind
    
  #   xlsx = Roo::Spreadsheet.open(temp_file.path, extension: :xlsx)
  #   sheet = xlsx.sheet(0)
  #   data = sheet.each_row_streaming.map { |row| row.map(&:value) }.flatten.join(' ')


  #   puts "DATA TYPE BELOW"
  #   puts data.class

  #   # Embedding process
  #   client = OpenaiService.new
  #   embedding = client.generate_embeddings(data)
    
  #   embedding
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown_to_html(text)
    renderer = Redcarpet::Render::HTML.new
    markdown = Redcarpet::Markdown.new(renderer, autolink: true, tables: true)
    markdown.render(text).html_safe
  end
end

app/helpers/inputs_helper.rb
module InputsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/inputs/_response.html.erb
<turbo-stream action="append" target="response_area">
  <template>
    <div markdown="1"><strong>Response:</strong> <%= markdown_to_html(response) %></p>
  </template>
</turbo-stream>

app/views/inputs/index.html.erb
<h1>Hello, <%= @user.name %>!</h1>

<%= form_with url: send_message_path, method: :post, local: false, data: { turbo: true } do |form| %>
  <div>
    <p>
      <%= form.label :message, "Send your message:" %>
    <p>
    <%= form.text_area :message, rows: 5, columns: 50, placeholder: "How can I help you today?" %>
    <%= form.submit "Send" %>
  <div>
<% end %>

<%= form_with model: @user, local: true, url: user_path(@user) do |form| %>
  <div>
    <%= form.label :closet, "Upload Your Closet" %>
    <%= form.file_field :closet %>
  </div>
  <%= form.submit %>
<% end %>

<%= form_with model: @user, local: true, url: user_path(@user) do |form| %>
  <div>
    <%= form.label :outfits_history, "Upload Your Outfits History" %>
    <%= form.file_field :outfits_history %>
  </div>
  <%= form.submit %>
<% end %>
<div>
  <%= button_to 'Home', root_path, method: :get%>
</div>

<div id="response_area"></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AITest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>

  <%= javascript_tag 'application', 'data-turbo-track': 'reload' %>
</html>

app/views/users/index.html.erb
<h1> Users </h1>

<ol>
  <% @users.each do |user| %>
    <li><%= link_to user.name, user_input_path(id: user.id) %></li>
  <% end %>
</ol>

app/views/users/new.html.erb
<%= form_with model: @user, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :password_confirmation %>
    <%= form.text_field :password_confirmation %>
  </div>
  <%= form.submit "Sign up" %>
<% end %>

app/views/users/show.html.erb
<h1>Hello, <%= @user.name %>!</h1>

<h3>Your outfits history: <%= @user.outfits_history.attached? ?  "ALREADY UPLOADED" : "TO BE UPLOADED" %></h3>
<div>
  <%= button_to 'DELETE', delete_outfits_history_path, method: :delete%>
</div>

<h3>Your closet: <%= @user.closet.attached? ? "ALREADY UPLOADED" : "TO BE UPLOADED" %></h3>
<div>
  <%= button_to 'DELETE', delete_closet_path, method: :delete%>
</div>
<br>
<div>
  <%= button_to 'Get Outfit Suggestions!', user_input_path(id: @user.id), method: :get%>
</div>
<br>
<div>
  <%= button_to 'Log out', logout_path, method: :delete%>
</div>